return {
    enabled = true,
    fontSize = 18,
    fontColor = { 0.00, 0.82, 0.88, 1.0 },
    highlightFile = 'None',
    highlightClickable = true,
    highlightAutoPlace = true,
    highlightAutoPlaceBy = 'Widest element',
    highlightSpacing = 7,
    highlightOffsetX = 0,
    highlightOffsetY = 0,
    highlightWidth = 220,
    highlightHeight = 74,
    highlightColor = { 0.00, 0.82, 0.88, 1.0 },
    highlightOpacity = 95,
    iconEnabled = false,
    iconFile = 'aoe_range_00.png',
    iconSize = 22,
    iconOffsetX = -42,
    iconOffsetY = -54,
    iconAnchorTo = 'Name',
    iconAnchorPoint = 'Center',
};
