return {
    enabled = true,
    fontSize = 18,
    fontColor = { 0.00, 0.82, 0.88, 1.0 },
    iconEnabled = false,
    iconSize = 22,
    iconOffsetX = -42,
    iconOffsetY = -54,
    iconAnchorTo = 'Name',
    iconAnchorPoint = 'Left',
    highlightEnabled = false,
    backgroundFile = 'None',
    autoPlaceBackground = true,
    backgroundAutoPlaceAnchor = 'Widest element',
    backgroundSpacing = 7,
    backgroundWidth = 300,
    backgroundHeight = 90,
    backgroundOffsetX = 0,
    backgroundOffsetY = 0,
    backgroundColor = { 0.00, 0.82, 0.88, 0.95 },
};
