local line = "    ['Da\'Vhu']                                = { type = 'Adventuring Fellow', icon = 'Dialogue.png' "
print('has eq', line:find('= {'))
print('not comma', tostring(not line:find(',%s*$')))
print('iconPos', line:find('icon'))
local iconPos = line:find('icon')
local eqPos = line:find('=', iconPos)
print('eqPos', eqPos)
local afterEq = line:sub(eqPos + 1)
print('afterEq', afterEq)
afterEq = afterEq:match('^%s*(.*)')
print('afterEq2', afterEq)
print('first', afterEq:sub(1,1))
