local defaults = {
    enabled = true,
    width = 500,
    height = 229,
    offsetX = 0,
    offsetY = 0,
    texture = 'None',
    drgArtworkOpacity = 100,
    color = { 0.0, 0.0, 0.0, 0.0 },
    borderColor = { 0.0, 0.0, 0.0, 0.0 },
    borderSize = 0,

    drgNameSettings = {
        enabled = true,
        textSize = 22,
        color = { 1.0, 1.0, 1.0, 1.0 },
        outlineEnabled = true,
        outlineColor = { 0.0, 0.0, 0.0, 1.0 },
        outlineSize = 2,
        offsetX = 80,
        offsetY = -58,
        anchorTo = 'Plate',
        anchorPoint = 'Center',
    },
    drgHpBarSettings = {
        enabled = true,
        width = 225,
        height = 14,
        offsetX = 80,
        offsetY = -30,
        color = { 0.20, 0.95, 0.34, 0.95 },
        backgroundColor = { 0.02, 0.02, 0.02, 0.70 },
        borderColor = { 0.0, 0.0, 0.0, 1.0 },
        borderSize = 0,
        cornerRadius = 3,
        texture = 'Solid',
        textureStrength = 100,
        showValue = false,
        showPercent = true,
        showAtPercent = 100,
        lowColorEnabled = true,
        lowColorPercent = 25,
        lowColor = { 1.0, 0.15, 0.10, 1.0 },
        lowAnimationEnabled = false,
        lowAnimation = 'Important',
        lowAnimationSpeed = 40,
        lowAnimationColor = { 1.0, 1.0, 1.0, 0.35 },
        textOffsetX = 0,
        textOffsetY = 0,
        useSmallFont = true,
        fontSize = 7,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        textOutlineEnabled = true,
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineSize = 1,
        anchorTo = 'Plate',
        anchorPoint = 'Center',
    },
    drgTpBarSettings = {
        enabled = true,
        width = 225,
        height = 9,
        offsetX = 80,
        offsetY = -9,
        color = { 1.0, 0.70, 0.18, 1.0 },
        color2 = { 0.80, 0.45, 1.0, 0.95 },
        color3 = { 0.35, 0.75, 1.0, 0.95 },
        fullColor = { 1.0, 0.70, 0.18, 1.0 },
        backgroundColor = { 0.02, 0.02, 0.02, 0.70 },
        borderColor = { 0.0, 0.0, 0.0, 1.0 },
        borderSize = 0,
        cornerRadius = 3,
        texture = 'Solid',
        textureStrength = 100,
        showValue = false,
        showPercent = false,
        showAtPercent = 0,
        segmented = true,
        segmentGap = 4,
        textOffsetX = 0,
        textOffsetY = 0,
        useSmallFont = true,
        fontSize = 7,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        textOutlineEnabled = true,
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineSize = 1,
        anchorTo = 'Plate',
        anchorPoint = 'Center',
    },
    drgEnmitySettings = {
        allyIconFile = 'warning-dimond.png',
        allyColor = { 1.0, 0.25, 0.20, 1.0 },
        allyOffsetX = 205,
        allyOffsetY = -57,
        allyIconSize = 30,
    },
    drgCallWyvernSettings = {
        enabled = true,
        offsetX = -105,
        offsetY = -15,
        useSmallFont = true,
        fontSize = 16,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        activeTextColor = { 0.30, 1.0, 0.45, 1.0 },
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineSize = 2,
    },
    drgSpiritLinkSettings = {
        enabled = true,
        width = 26,
        height = 39,
        offsetX = -36,
        offsetY = 71,
        color = { 0.10, 0.55, 1.00, 1.0 },
        backgroundColor = { 0.02, 0.02, 0.02, 0.70 },
        borderColor = { 0.0, 0.0, 0.0, 0.0 },
        borderSize = 0,
        cornerRadius = 3,
        texture = 'Soft Gray',
        textureStrength = 100,
        fillDirection = 'Bottom to top',
        labelDisplayMode = 'None',
        showValue = false,
        showPercent = true,
        textOffsetX = 0,
        textOffsetY = 0,
        useSmallFont = true,
        fontSize = 10,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        textOutlineEnabled = true,
        activeTextColor = { 0.30, 1.0, 0.45, 1.0 },
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineSize = 2,
    },
    drgSpiritBondSettings = {
        enabled = true,
        width = 26,
        height = 39,
        offsetX = 39,
        offsetY = 71,
        color = { 0.95, 0.12, 0.10, 1.0 },
        backgroundColor = { 0.02, 0.02, 0.02, 0.70 },
        borderColor = { 0.0, 0.0, 0.0, 0.0 },
        borderSize = 0,
        cornerRadius = 3,
        texture = 'Soft Gray',
        textureStrength = 100,
        fillDirection = 'Bottom to top',
        labelDisplayMode = 'None',
        showValue = false,
        showPercent = true,
        textOffsetX = 0,
        textOffsetY = 0,
        useSmallFont = true,
        fontSize = 10,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        textOutlineEnabled = true,
        activeTextColor = { 0.30, 1.0, 0.45, 1.0 },
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineSize = 2,
    },
};

local function Copy(value)
    if type(value) ~= 'table' then
        return value;
    end

    local result = {};
    for key, child in pairs(value) do
        result[key] = Copy(child);
    end
    return result;
end

return {
    Get = function()
        return Copy(defaults);
    end,
};
