return {
    font = {
        family = 'Default',
        largeFamily = 'Default',
        smallFamily = 'Default',
    },
    targeting = {
        enableRightClickAttack = true,
        rightClickAttackRange = 4.5,
        enemyPlateRange = 49.9,
        enemyActiveDetailRange = 25.0,
        pcDistanceScaleStart = 2.0,
        pcDistanceScaleEnd = 8.0,
        pcDistanceScaleMax = 2.65,
        globalPlateOffsetX = 0,
        globalPlateOffsetY = 0,
        plateDistanceScales = {
            self = { start = 2.0, finish = 8.0, max = 2.65 },
            pc = { start = 2.0, finish = 8.0, max = 2.65 },
            trust = { start = 2.0, finish = 8.0, max = 2.65 },
            enemy = { start = 2.0, finish = 8.0, max = 2.65 },
            npc = { start = 2.0, finish = 8.0, max = 2.65 },
            object = { start = 2.0, finish = 8.0, max = 2.65 },
            pet = { start = 2.0, finish = 8.0, max = 2.65 },
        },
        platePositionOffsets = {
            self = { x = 0, y = 0 },
            pc = { x = 0, y = 0 },
            trust = { x = 0, y = 0 },
            enemy = { x = 0, y = 0 },
            npc = { x = 0, y = 0 },
            object = { x = 0, y = 0 },
            pet = { x = 0, y = 0 },
        },
        hideNativeTargetArrow = true,
        hideNativePartyTargetUi = true,
        hideNativeNamesOnLoad = true,
        enablePetPlateTargeting = true,
        blockPlateClicksWhenImguiCapturesMouse = true,
        plateClickNoGoZonesEnabled = false,
        plateClickNoGoZonesVisible = false,
        plateClickNoGoZones = {
            { name = 'Chat', enabled = false, x = 0, y = 960, width = 760, height = 480, color = { 1.0, 0.15, 0.15, 1.0 } },
            { name = 'Bottom bar', enabled = false, x = 760, y = 1160, width = 1160, height = 280, color = { 0.15, 0.75, 1.0, 1.0 } },
            { name = 'Right UI', enabled = false, x = 1920, y = 0, width = 640, height = 1440, color = { 1.0, 0.80, 0.10, 1.0 } },
            { name = 'Left UI', enabled = false, x = 0, y = 0, width = 360, height = 960, color = { 0.40, 1.0, 0.25, 1.0 } },
        },
        performanceSafetyMode = false,
        performanceSafetyCombatOnly = true,
        performanceSafetySkipPc = false,
        performanceSafetySkipTrust = false,
        performanceSafetySkipNpc = false,
        performanceSafetySkipPet = false,
        performanceSafetyImportantEnemiesOnly = false,
        performanceSafetySkipPeer = false,
        performanceMode = 'Auto',
    },
    mouseControls = {
        enableBothButtonForward = false,
        enableBothButtonSteer = false,
        invertSteer = false,
        steerDeadzone = 1.5,
    },
    cursorOverlay = {
        enabled = false,
        shape = 'Ring',
        radius = 13,
        trailLagReduction = 0,
        showCenterMark = false,
        outerEnabled = true,
        innerEnabled = true,
        centerEnabled = false,
        ringColor = { 1.0, 1.0, 1.0, 1.0 },
        accentColor = { 0.17, 0.84, 0.87, 1.0 },
        centerColor = { 0.17, 0.84, 0.87, 1.0 },
    },
    enmity = {
        enabled = true,
        mode = 'healer',
        offsetX = -108,
        offsetY = -17,
        iconSize = 31,
    },
    resting = {
        enabled = true,
        displayMode = 'Bar',
        width = 180,
        height = 12,
        ringSize = 88,
        ringThickness = 10,
        offsetX = 0,
        offsetY = 38,
        firstTickOffset = 1,
        repeatTickOffset = 0,
        mpTickThreshold = 12,
        enableLogoutCountdown = true,
        hideAtFullHp = false,
        hideAtFullMp = false,
        color = { 0.55, 0.95, 0.35, 1.0 },
        backgroundColor = { 0.10, 0.10, 0.10, 1.0 },
        borderColor = { 1.0, 1.0, 1.0, 1.0 },
        borderSize = 0,
        textColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineEnabled = false,
        textOutlineColor = { 1.0, 1.0, 1.0, 1.0 },
        textOutlineSize = 1,
        fontSize = 12,
    },
    fishing = {
        enabled = true,
        enableRightClickFish = true,
        enableRightClickGathering = true,
        enableRightClickMining = true,
        enableRightClickHarvesting = true,
        enableRightClickLogging = true,
        enableRightClickExcavation = true,
        iconFile = 'fishing_01.png',
        offsetX = 0,
        offsetY = 38,
        iconSize = 42,
        showLabel = true,
        labelFontSize = 12,
        labelOffsetY = 0,
        labelColor = { 1.0, 1.0, 1.0, 1.0 },
        labelOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        labelOutlineSize = 2,
    },
    crafting = {
        enabled = true,
        displayMode = 'Icon',
        previewResultName = 'High-Quality',
        offsetX = 0,
        offsetY = 38,
        iconSize = 42,
        showLabel = true,
        labelFontSize = 12,
        labelOffsetY = 0,
        labelColor = { 1.0, 1.0, 1.0, 1.0 },
        labelOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        labelOutlineSize = 2,
        textFontSize = 14,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        textOutlineSize = 2,
    },
    quickMenu = {
        enabled = true,
        openOnRightClick = true,
        modifier = 'None',
        width = 270,
        iconsEnabled = true,
        iconSize = 22,
        backgroundColor = { 0.02, 0.02, 0.07, 0.96 },
        borderColor = { 0.25, 0.25, 0.36, 1.0 },
        borderSize = 1,
        textColor = { 1.0, 1.0, 1.0, 1.0 },
        headerColor = { 1.0, 0.84, 0.0, 1.0 },
        linkColor = { 0.48, 0.82, 1.0, 1.0 },
        presets = {
            iconTheme = 'FFXI',
            entries = {
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
                { mainJob = 'None', subJob = 'None' },
            },
        },
        pc = {
            examine = true,
            catseyeProfile = true,
            follow = true,
            inviteToParty = true,
            requestJoinParty = true,
            invitePartyToAlliance = true,
            passPartyLeader = true,
            passAllianceLeader = true,
        },
        self = {
            acceptInvite = true,
            declineInvite = true,
            leaveParty = true,
            leaveAlliance = true,
            cancelPartyRequest = true,
            autogroup = true,
            ignoreTrust = true,
            hideTrust = true,
            emoteTrust = true,
        },
        trust = {
            dismiss = true,
            dismissAll = true,
            confirmDismissAll = true,
        },
        npc = {
            showType = true,
            showInfo = true,
            openLink = true,
            maxInfoChars = 420,
            maxInfoLines = 10,
            maxQuestLinks = 4,
        },
    },
    peer = {
        activationModifier = 'Shift',
        maxRange = 49.9,
        inspectorWidth = 430,
        zoom = 3.0,
        displayMode = 'Text',
        iconStyle = 'round',
        iconSize = 18,
        textFontSize = 14,
        textColor = { 0.94, 0.94, 0.90, 1.0 },
        textOutlineSize = 1,
        textOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        iconOffsetX = -190,
        iconOffsetY = -16,
        showBackground = true,
        backgroundOffsetX = 0,
        backgroundOffsetY = 0,
        backgroundWidth = 460,
        backgroundHeight = 72,
        backgroundColor = { 0.0, 0.0, 0.0, 0.45 },
        backgroundOpacity = 45,
        backgroundBorderSize = 0,
        backgroundBorderColor = { 0.0, 0.0, 0.0, 1.0 },
        showName = true,
        nameOffsetX = 0,
        nameOffsetY = -54,
        nameFontSize = 32,
        nameColor = { 1.0, 1.0, 1.0, 1.0 },
        nameOutlineSize = 3,
        nameOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        showHpBar = true,
        hpBarOffsetX = 0,
        hpBarOffsetY = 0,
        hpBarWidth = 437,
        hpBarHeight = 16,
        hpBarColor = { 0.0, 0.75, 0.16, 1.0 },
        hpBarBackgroundColor = { 0.05, 0.05, 0.05, 0.85 },
        hpBarBorderSize = 0,
        hpBarBorderColor = { 0.0, 0.0, 0.0, 1.0 },
        showHpPercent = true,
        showHpValue = true,
        hpPercentOffsetX = 0,
        hpPercentOffsetY = 0,
        hpPercentFontSize = 12,
        hpPercentColor = { 1.0, 1.0, 1.0, 1.0 },
        hpPercentOutlineSize = 2,
        hpPercentOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        showJob = true,
        jobDisplay = 'Text',
        jobIconTheme = 'FFXI',
        jobIconSize = 18,
        jobOffsetX = -190,
        jobOffsetY = -16,
        jobFontSize = 12,
        jobColor = { 1.0, 1.0, 1.0, 1.0 },
        jobOutlineSize = 2,
        jobOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        showLevel = true,
        levelOffsetX = -145,
        levelOffsetY = -16,
        levelFontSize = 12,
        levelColor = { 1.0, 1.0, 1.0, 1.0 },
        levelOutlineSize = 2,
        levelOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        levelDifficultyColorsEnabled = false,
        levelTwColor = { 0.55, 0.55, 0.55, 1.0 },
        levelEpColor = { 0.45, 0.72, 1.0, 1.0 },
        levelDcColor = { 0.40, 0.90, 0.45, 1.0 },
        levelEmColor = { 1.0, 1.0, 1.0, 1.0 },
        levelTColor = { 1.0, 0.90, 0.35, 1.0 },
        levelVtColor = { 1.0, 0.62, 0.25, 1.0 },
        levelItColor = { 1.0, 0.30, 0.30, 1.0 },
        showRange = true,
        showDistance = true,
        rangeOffsetX = 92,
        rangeOffsetY = -54,
        rangeFontSize = 12,
        rangeColor = { 1.0, 1.0, 1.0, 1.0 },
        rangeOutlineSize = 2,
        rangeOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        showId = false,
        idOffsetX = 0,
        idOffsetY = 24,
        idFontSize = 7,
        idColor = { 0.65, 0.90, 1.0, 1.0 },
        idOutlineSize = 2,
        idOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        idBoxEnabled = true,
        idBoxSize = 18,
        idBoxColor = { 0.45, 0.15, 0.15, 0.90 },
        idBoxBorderSize = 0,
        idBoxBorderColor = { 1.0, 1.0, 1.0, 1.0 },
        idCornerRadius = 4,
        showAggro = true,
        showBehavior = true,
        aggroOffsetX = -95,
        aggroOffsetY = -16,
        aggroIconSize = 18,
        aggroFontSize = 12,
        aggroColor = { 1.0, 1.0, 1.0, 1.0 },
        aggroOutlineSize = 2,
        aggroOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
        showDetection = true,
        showDetects = true,
        showLinks = true,
        detectionOffsetX = -55,
        detectionOffsetY = -16,
        detectionIconSize = 18,
        showImmunities = true,
        immunityOffsetX = 45,
        immunityOffsetY = -16,
        immunityIconSize = 18,
        showModifiers = true,
        showWeakTo = true,
        showResists = true,
        modifierOffsetX = 120,
        modifierOffsetY = -16,
        modifierIconSize = 18,
        showModifierValues = true,
        modifierValueFontSize = 12,
        modifierValueColor = { 1.0, 1.0, 1.0, 1.0 },
        modifierValueOutlineSize = 2,
        modifierValueOutlineColor = { 0.0, 0.0, 0.0, 1.0 },
    },
};
